name: 'keptn-update-action'
description: 'Automated releases for GitOps Projects'
author: 'The Keptn Contributors'
inputs:
  inputPath:
    description: 'The path to the input file'
    default: ""
    required: false
  outputPath:
    description: 'The path to the output file'
    default: ""
    required: false
  version:
    description: 'The version to update'
    default: ""
    required: false
  bump:
    description: 'The bump type'
    default: "false"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-i ${{ inputs.inputPath }}'
    - '-o ${{ inputs.outputPath }}'
    - '-v ${{ inputs.version }}'
    - '-b ${{ inputs.bump }}'



